### ISSUE TITLE
Maak User-Authenticator

### ISSUE THREAD

**Issue by Th3D0nut** [Th3D0nut/kunst_uitleen#12]
(Ideas, feel free to add or remove things)

Create a user authentication system on the basis of the input of the front end side (Expected input: Username and Password).

Validate if Username matches the password.
Send a signal that it does and supply data consisting of that user account.

Idea: encrypt/decrypt this data. Example: input arrives encrypted, then program decrypts it and we validate the user. After this we send back the validation and account.

**Comment by SSchotten** [comment]
Maaike deelde vorige week deze link over authenticatie in Django: https://docs.djangoproject.com/en/4.0/topics/auth/default/ 

Ik heb er nog niet echt goed naar gekeken, maar volgens mij doet het precies wat je wilt bereiken met dit issue. 

Deze `User` objects kunnen dan wellicht weer gekoppeld worden aan een `UserProfile` object zoals schematisch getekend linksonder in https://github.com/Th3D0nut/kunst_uitleen/blob/main/docs/models_and_operations.png

**Comment by Th3D0nut** [comment]
Ja, als ik het zo bekijk doet dit precies wat ik wil. Goed uitgezocht!

**Comment by SSchotten** [comment]
@Th3D0nut we hebben nu volgens mij een richting om dit issue aan te pakken gevonden, maar het is nog niet gemaakt en gereviewed? 

Het lijkt me daarom handig om het issue open te houden - het heet immers '_maak_ User-Authenticator' ;) Dan is bovenstaande info ook meteen beschikbaar voor als je het gaat maken.
